
version: 2

models:                             #### UPDATE ME
    - name: dm_all_cities_per_month
      description: "monthly stats across all cities"
      columns:
          - name: trunc_to_mon
            description: "Grouping for this table - datetime truncated to month"
            tests:
                - not_null

    - name: dm_chicago_crimes
      description: "staging model for Austin data"
      columns:
          - name: id
            description: "The primary key for this table"
